//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKho
    {
        public int Id { get; set; }
        public int HangHoaId { get; set; }
        public int KhoId { get; set; }
        public System.DateTime ThoiGianNhapKho { get; set; }
        public int SoLuong { get; set; }
        public int UserIdNhap { get; set; }
    }
}
