//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonMua
    {
        public int Id { get; set; }
        public int NhanVienId { get; set; }
        public int NhaCungCapId { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    }
}
