//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int Id { get; set; }
        public string MaNV { get; set; }
        public string HoTenNV { get; set; }
        public string DiaChi { get; set; }
        public string Sdt { get; set; }
        public string Email { get; set; }
        public string Cmnd { get; set; }
        public int CapBac { get; set; }
        public Nullable<decimal> Luong { get; set; }
    }
}
